// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjhmkcqrmxpbcrihrimu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqaG1rY3FybXhwYmNyaWhyaW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDc3MTAsImV4cCI6MjA2MDQ4MzcxMH0.IvqKtUhl5APCi0fU2ImoiMZJABby36AG3iwelLlHK8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);